Implement UpdateCertificate transaction
target/consensource-processor pull request #21
Opened 2021-01-26 20:43 UTC by pa3ng

## Proposed change/fix

- [ ] Implement UpdateCertificate transaction
- [ ] Minor code formatting
- [ ] Update Cargo.lock

_Note:_ the `common` crate in the `Cargo.toml` is temporarily set to the [rsd-update-cert](https://github.com/target/consensource-common/pull/19) branch. That PR should be merged first before merging this one.

## Types of changes

What types of changes does this pull request introduce to ConsenSource? _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (could be a small readme update, documentation contribution, etc.)

## How to run/test

tbd

2021-01-26 20:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/target/consensource-processor?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/target/consensource-processor?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/target/consensource-processor?pullRequest=21) it.</sub>

2021-02-02 20:44 UTC, trevormcdonald requested changes

2021-02-03 15:18 UTC, pa3ng commented
Fixing broken tests

2021-02-04 15:19 UTC, trevormcdonald commented
I'm seeing some clippy warnings, for reference I am running
```
$ cargo clippy --version
clippy 0.0.212 (e1884a8e 2020-12-29)
```

2021-02-04 16:20 UTC, pa3ng commented
> I'm seeing some clippy warnings, for reference I am running
> 
> ```
> $ cargo clippy --version
> clippy 0.0.212 (e1884a8e 2020-12-29)
> ```

I'm on the same version 👍 interestingly, it's asking me to remove the `.clone()` in `&organization.clone().get_id()` which i saw in your recent PR 🤷🏻‍♂️ removing...

2021-02-04 16:39 UTC, trevormcdonald submitted a review, later dismissed

2021-02-05 14:35 UTC, trevormcdonald approved these changes

2021-02-05 20:17 UTC, merged